// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Task$BsTaskorama = require("./task.bs.js");

console.log("Hello Taskorama in ReasonML!");

var myTask = Task$BsTaskorama.chain((function (x) {
        return Task$BsTaskorama.of_(x + 2 | 0);
      }), Task$BsTaskorama.map((function (x) {
            return x + 2 | 0;
          }), Task$BsTaskorama.map((function (l) {
                return List.fold_left((function (acc, curr) {
                              return acc + curr | 0;
                            }), 0, l);
              }), Task$BsTaskorama.ap(Task$BsTaskorama.wait(2000, 2), Task$BsTaskorama.ap(Task$BsTaskorama.wait(1000, 2), Task$BsTaskorama.of_((function (x, y) {
                            return /* :: */[
                                    x,
                                    /* :: */[
                                      y,
                                      /* [] */0
                                    ]
                                  ];
                          })))))));

var stop = Task$BsTaskorama.fork((function (prim) {
        console.log(prim);
        return /* () */0;
      }), (function (prim) {
        console.log(prim);
        return /* () */0;
      }), myTask);

setTimeout((function () {
        return Curry._1(stop, /* () */0);
      }), 1500);

exports.myTask = myTask;
exports.stop = stop;
/*  Not a pure module */
